GO
/****** Object:  Table [dbo].[ENTREVISTA]    Script Date: 2020-10-30 16:40:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ENTREVISTA](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[vacante] [int] NOT NULL,
	[prospecto] [int] NOT NULL,
	[fecha_entrevista] [date] NULL,
	[notas] [varchar](max) NULL,
	[reclutado] [bit] NULL,
 CONSTRAINT [PK_ENTREVISTA] PRIMARY KEY CLUSTERED 
(   [vacante] ASC,
	[prospecto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/****** Object:  Table [dbo].[PROSPECTO]    Script Date: 2020-10-30 16:40:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROSPECTO](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NULL,
	[correo] [varchar](50) NULL,
	[fecha_registro] [date] NULL,
 CONSTRAINT [PK_PROSPECTO] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[VACANTE]    Script Date: 2020-10-30 16:40:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VACANTE](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[area] [varchar](50) NULL,
	[sueldo] [money] NULL,
	[activo] [bit] NULL,
 CONSTRAINT [PK_VACANTE] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ENTREVISTA]  WITH CHECK ADD  CONSTRAINT [FK_ENTREVISTA_PROSPECTO] FOREIGN KEY([prospecto])
REFERENCES [dbo].[PROSPECTO] ([id])
GO
ALTER TABLE [dbo].[ENTREVISTA] CHECK CONSTRAINT [FK_ENTREVISTA_PROSPECTO]
GO
ALTER TABLE [dbo].[ENTREVISTA]  WITH CHECK ADD  CONSTRAINT [FK_ENTREVISTA_VACANTE] FOREIGN KEY([vacante])
REFERENCES [dbo].[VACANTE] ([id])
GO
ALTER TABLE [dbo].[ENTREVISTA] CHECK CONSTRAINT [FK_ENTREVISTA_VACANTE]
GO